{
 "title": "Dragonite",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dragonite_config_fort_location_delay, instance) "
    }
   },
   {
    "name": "inter",
    "label": "Interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d"
   },
   { "name": "area", "label": "Area", "query": { "query": "label_values(area)" } },
   { "name": "origin", "label": "Origin", "query": { "query": "label_values(origin)" } }
  ]
 },
 "panels": [
  {
   "title": "Total RPC Responses / $inter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Success\", instance=~\"$instance\"}[$inter:]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Account Suspended Rate Limited\", instance=~\"$instance\"}[$inter:]))",
     "legendFormat": "Account Suspended Rate Limited"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Action Error\", instance=~\"$instance\"}[$inter:]))",
     "legendFormat": "Action Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Cancelled Request\", instance=~\"$instance\"}[$inter:]))",
     "legendFormat": "Cancelled Request"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"No Retries Error\", instance=~\"$instance\"}[$inter:]))",
     "legendFormat": "No Retries Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Parsing Error\", instance=~\"$instance\"}[$inter:]))",
     "legendFormat": "Parsing Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Undefined\", instance=~\"$instance\"}[$inter:]))",
     "legendFormat": "Undefined"
    },
    {
     "expr": "sum(max_over_time(rotom_workers_total[$inter])-max_over_time(rotom_workers_active[$inter]))",
     "legendFormat": " Workers Inactive"
    },
    {
     "expr": "sum(max_over_time(rotom_workers_total[$inter]))",
     "legendFormat": " Workers Total"
    }
   ]
  },
  {
   "title": "IV Rate / $inter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum(golbat_pokemon_count_iv{area=~\"$area\"})[$inter:])/max(sum(rotom_workers_active)[$inter])",
     "legendFormat": "IV Rate / $inter"
    },
    {
     "expr": "max(sum(rotom_workers_active)[$inter])",
     "legendFormat": "Total Workers"
    }
   ]
  },
  {
   "title": "RPC Per Active Workers / $inter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Success\", instance=~\"$instance\"}[$inter:]))/sum(rotom_workers_active)",
     "legendFormat": "RPC per Active Workers"
    },
    { "expr": "sum(rotom_workers_active)", "legendFormat": "Active Workers" }
   ]
  },
  {
   "title": "Location Handling Time / $area / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  rate(dragonite_location_handled_sum{area=~\"$area\", exported_job=\"pokemon\", instance=~\"$instance\"}[$inter]) /\n  rate(dragonite_location_handled_counter{area=~\"$area\", exported_job=\"pokemon\", instance=~\"$instance\"}[$inter])\n)",
     "legendFormat": "Pokemon"
    },
    {
     "expr": "avg(\n  rate(dragonite_location_handled_sum{area=~\"$area\", exported_job=\"fort\", instance=~\"$instance\"}[$inter]) /\n  rate(dragonite_location_handled_counter{area=~\"$area\", exported_job=\"fort\", instance=~\"$instance\"}[$inter])\n)",
     "legendFormat": "Fort"
    },
    {
     "expr": "avg(\n  rate(dragonite_location_handled_sum{area=~\"scout\", exported_job=\"scout\", instance=~\"$instance\"}[$inter]) /\n  rate(dragonite_location_handled_counter{area=~\"scout\", exported_job=\"scout\", instance=~\"$instance\"}[$inter])\n)",
     "legendFormat": "Scout"
    },
    {
     "expr": "avg(\n  rate(dragonite_location_handled_sum{area=~\"$area\", exported_job=\"quest\", instance=~\"$instance\"}[$inter]) /\n  rate(dragonite_location_handled_counter{area=~\"$area\", exported_job=\"quest\", instance=~\"$instance\"}[$inter])\n)",
     "legendFormat": "Quest"
    }
   ]
  },
  {
   "title": "GMO Retries / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"0\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "0"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"1\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "1"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"2\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "2"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"3\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "3"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"4\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "4"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"5\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "5"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"6\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "6"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"7\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "7"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"8\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "8"
    }
   ]
  },
  {
   "title": "RPC Status / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Success\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Account Suspended Rate Limited\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Account Suspended Rate Limited"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Action Error\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Action Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Cancelled Request\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Cancelled Request"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"No Retries Error\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "No Retries Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Parsing Error\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Parsing Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Undefined\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Undefined"
    }
   ]
  },
  {
   "title": "GMO Hits / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(dragonite_gmo_hits{status=~\"Success\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_hits{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(dragonite_gmo_hits{status=~\"Empty\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_hits{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Empty"
    },
    {
     "expr": "sum(increase(dragonite_gmo_hits{status=~\"Failed\", instance=~\"$instance\"}[$inter:])) / sum(increase(dragonite_gmo_hits{status=~\".*\", instance=~\"$instance\"}[$inter:])) * 100",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Auth PTC / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dragonite_auth_ptc{instance=~\"$instance\"}[$inter])* $inter",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Account Status / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dragonite_account_status{instance=~\"$instance\"}[$inter])*$inter",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Quest Handling Time / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(dragonite_location_handled_sum{exported_job=\"quest\", instance=~\"$instance\"}[$inter]) / rate(dragonite_location_handled_counter{exported_job=\"quest\", instance=~\"$instance\"}[$inter])",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Invasion Queue Size / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dragonite_invasions_queue_size{instance=~\"$instance\"}[$inter])* $inter",
     "legendFormat": "Queue size"
    }
   ]
  },
  {
   "title": "Scout Queue / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dragonite_scout_queue_size{instance=~\"$instance\"}",
     "legendFormat": "Queue size"
    }
   ]
  },
  {
   "title": "Invasion time queued / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (type) (\n  rate(dragonite_invasions_time_queued{instance=~\"$instance\"}[$inter]) /\n  rate(dragonite_invasions_confirmed_types{instance=~\"$instance\"}[$inter])\n)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(avg by (type) (\n  rate(invasions_time_queued{instance=~\"$instance\"}[$inter]) /\n  rate(invasions_confirmed_types{instance=~\"$instance\"}[$inter])\n))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Invasion Status / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dragonite_invasions_status{instance=~\"$instance\"}[$inter])*$inter",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Invasion Confirmed / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dragonite_invasions_confirmed_types{instance=~\"$instance\"}[$inter])*$inter",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Invasion time left / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "avg by (type) (\n  rate(dragonite_invasions_time_left{instance=~\"$instance\"}[$inter]) /\n  rate(dragonite_invasions_confirmed_types{instance=~\"$instance\"}[$inter])\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Config in time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dragonite_config_allow_consecutive_failures{instance=~\"$instance\"}",
     "legendFormat": "allow_consecutive_failures"
    },
    {
     "expr": "dragonite_config_fort_location_delay{instance=~\"$instance\"}",
     "legendFormat": "fort_location_delay"
    },
    {
     "expr": "dragonite_config_location_delay{instance=~\"$instance\"}",
     "legendFormat": "location_delay"
    },
    {
     "expr": "dragonite_config_max_retries{instance=~\"$instance\"}",
     "legendFormat": "max_retries"
    },
    {
     "expr": "dragonite_config_no_pokemon_delay{instance=~\"$instance\"}",
     "legendFormat": "no_pokemon_delay"
    },
    {
     "expr": "dragonite_config_rpc_12_disable_count{instance=~\"$instance\"}",
     "legendFormat": "rpc_12_disable_count"
    }
   ]
  }
 ]
}